<b>Магазин женской одежды</b> <tg-emoji emoji-id="5431449001532594346">⚡️</tg-emoji>

<tg-emoji emoji-id="5411520005386806155">🏁</tg-emoji> <b>Задача:</b>
Запустить рекламу на сообщения в группу ВК по продаже одежды. Ранее реклама не запускалась, главная цель — заявки.

<tg-emoji emoji-id="5350460637182993292">🎯</tg-emoji> <b>Результат:</b>
<tg-emoji emoji-id="5357471466919056181">🔘</tg-emoji> <b>58</b> лидов
<tg-emoji emoji-id="5357471466919056181">🔘</tg-emoji> <b>96 ₽</b> за лид
<tg-emoji emoji-id="5357471466919056181">🔘</tg-emoji> <b>5 606 ₽</b> затраты
<tg-emoji emoji-id="5357471466919056181">🔘</tg-emoji> <b>35</b> покупок из 58 лидов
<tg-emoji emoji-id="5357471466919056181">🔘</tg-emoji> Средний чек — <b>12 500 ₽</b>
<tg-emoji emoji-id="5357471466919056181">🔘</tg-emoji> Реклама <b>окупилась!</b>

<tg-emoji emoji-id="5427009714745517609">✅</tg-emoji> Скрин статистики <tg-emoji emoji-id="5470177992950946662">👇</tg-emoji>

<blockquote><tg-emoji emoji-id="5471883477219549006">💪</tg-emoji> Лид по 96 ₽ и конверсия в покупку 60% — отличный результат для магазина одежды. Вложения вернули с прибылью.</blockquote>

<tg-emoji emoji-id="5465665476971471368">❌</tg-emoji> <b>Задать вопрос</b> <tg-emoji emoji-id="5465665476971471368">❌</tg-emoji>

#ТаргетВК #СообществоВК #КейсМагазинОдежды
